sudo: required
dist: trusty
language: cpp

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - os: linux
    compiler: clang

addons:
  apt:
    packages:
    - build-essential
    - clang
    - qtbase5-dev
    - qtbase5-doc-html
    - qttools5-dev-tools
    - doxygen
    - graphviz
    - libqt5sql5-sqlite

before_install:
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt5 && brew link
  --force qt5; fi
- mkdir build
- mkdir build/longscroll
- mkdir build/simple
- mkdir build/demo

script:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    if [ "$CXX" == "clang++" ]; then
      QMAKECMD='qmake -qt=5 -spec linux-clang'
    else
      QMAKECMD='qmake -qt=5 -spec linux-g++-64'
    fi
  elif [ $TRAVIS_OS_NAME == osx ]; then
    if [ "$CXX" == "clang++" ]; then
      QMAKECMD='qmake -spec macx-clang'
    else
      QMAKECMD='qmake -spec macx-g++'
    fi
  fi
- pushd build/longscroll
- $QMAKECMD -v
- $QMAKECMD -r ../../src/longscroll-qt.pro "CONTINUOUS_INTEGRATION=1" "CONFIG+=release"
- make -j4
- make install
- if [ $TRAVIS_OS_NAME == linux ] && [ "$CXX" == "g++" ]; then make docs; fi
- make clean
- popd
- pushd build/simple
- $QMAKECMD -v
- $QMAKECMD -r ../../examples/simple/simple.pro "CONFIG+=release"
- make -j4
- make install
- make clean
- popd
- pushd build/demo
- $QMAKECMD -v
- $QMAKECMD -r ../../examples/demo/demo.pro "CONFIG+=release"
- make -j4
- make install
- make clean
- popd

before_deploy:
- export DOCZIPNAME="longscroll-qt-$TRAVIS_TAG"
- export ZIPNAME="$DOCZIPNAME-$TRAVIS_OS_NAME-$CC"
- pushd dist
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then
    pushd doc/html
    mv html doc
    XZ_OPT=-9 tar -cJf "../../../$DOCZIPNAME-doc-html.tar.xz" doc
    popd
    pushd doc/qhp
    pwd
    ls -al
    mv longscroll.qch longscroll-$TRAVIS_TAG.qch
    XZ_OPT=-9 tar -cJf "../../../$DOCZIPNAME-doc-qhp.tar.xz" *.qch
    popd
    rm -rf doc
  fi
- XZ_OPT=-9 tar -cJf "$ZIPNAME.tar.xz" *
- popd
- ls -al
- ls -al dist

deploy:
- provider: releases
  api_key:
    secure: Ca60pyC9KeMCPBoisrSCLG2laXYUzYBYm1TE3KP1Zpror+VZSbGvypu6Msbsu98UKiBKgchnICfBFiS58XS34oBx3c4uwEosq+aw5/AlyBMNXnnr9I1AY2GUsZUpQ9TLfg+WD8Vcxw6Huw6vGNuZNGg2wUNxIPwvKrOEk5ABufU1P8OvzRQf626OPWK4K7AlfnlTSWW2Z+6m4/pVUU2yjoEAbyQrPqYB7zedUzDLBdR/1iBRLz1lDT6+km+JLMCO4WpV6mq3ix9tJmEBUdtroJy+3S5IYXmYP31aNGTlODzDOdlfNebNw4lFp8JzOK90BNmM3K50lkPx1Q1eNa6VR7pgIYDyv2jltbEjgyKsnrRibo8ELxOEWZQu3Sk0aKgoNynm/0qUeVbMGBcssBrDha1lKebZYaJFYZMewgNHu9r/92thJughDEdaoBCyfB2YWMjOtQ85NysRmGCn9G8CP8PfX53y6SPUC52l/NK7QOh0g0QYWVQNaMfwMEnBfMESdKJxt/mecZYaMnA5bmk+OFngQWL3S40ZpUSLINcJ4xdZZBGTj5HtB7AdMIYxdS3i0EoKeWeicacUNUZi09p1NCPxXod+V8IPevg4rDwzh67aa+R6HzeWoEhBYRXEk/iMp4Tn+rkau4hpLuv0DGm1GlKYVyQEnhXtvWDy1z4l9AU=
  file:
  - "dist/$ZIPNAME.tar.xz"
  - "$DOCZIPNAME-doc-html.tar.xz"
  - "$DOCZIPNAME-doc-qhp.tar.xz"
  skip_cleanup: true
  on:
    repo: TripleWhy/longscroll-qt
    all_branches: true
    tags: true
    condition: ("$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++")
- provider: releases
  api_key:
    secure: Ca60pyC9KeMCPBoisrSCLG2laXYUzYBYm1TE3KP1Zpror+VZSbGvypu6Msbsu98UKiBKgchnICfBFiS58XS34oBx3c4uwEosq+aw5/AlyBMNXnnr9I1AY2GUsZUpQ9TLfg+WD8Vcxw6Huw6vGNuZNGg2wUNxIPwvKrOEk5ABufU1P8OvzRQf626OPWK4K7AlfnlTSWW2Z+6m4/pVUU2yjoEAbyQrPqYB7zedUzDLBdR/1iBRLz1lDT6+km+JLMCO4WpV6mq3ix9tJmEBUdtroJy+3S5IYXmYP31aNGTlODzDOdlfNebNw4lFp8JzOK90BNmM3K50lkPx1Q1eNa6VR7pgIYDyv2jltbEjgyKsnrRibo8ELxOEWZQu3Sk0aKgoNynm/0qUeVbMGBcssBrDha1lKebZYaJFYZMewgNHu9r/92thJughDEdaoBCyfB2YWMjOtQ85NysRmGCn9G8CP8PfX53y6SPUC52l/NK7QOh0g0QYWVQNaMfwMEnBfMESdKJxt/mecZYaMnA5bmk+OFngQWL3S40ZpUSLINcJ4xdZZBGTj5HtB7AdMIYxdS3i0EoKeWeicacUNUZi09p1NCPxXod+V8IPevg4rDwzh67aa+R6HzeWoEhBYRXEk/iMp4Tn+rkau4hpLuv0DGm1GlKYVyQEnhXtvWDy1z4l9AU=
  file:
  - "dist/$ZIPNAME.tar.xz"
  skip_cleanup: true
  on:
    repo: TripleWhy/longscroll-qt
    all_branches: true
    tags: true
    condition: ("$TRAVIS_OS_NAME" != "linux" || $CXX != "g++")
